#ifndef __SCARL_DEVICE_TYPE_MAP_H__
#define __SCARL_DEVICE_TYPE_MAP_H__

// Just as it is in SCARL Compiler

#define LIGHT_ACTUATOR 290
#define SERVO_ACTUATOR 291
#define SOUND_SENSOR 292
#define LIGHT_SENSOR 293
#define DISTANCE_SENSOR 294
#define TEMPERATURE_SENSOR 295

#endif